services:
  - type: web
    name: IntroCloud
    runtime: node
    repo: https://github.com/Koupy/IntroCloud
    buildCommand: npm install
    startCommand: npm run start
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgreSQL-IntroCloud
          property: connectionString

databases:
  - name: postgreSQL-IntroCloud
    region: frankfurt
    plan: free
